export const FILTERIDCONDITION = "FILTERIDCONDITION";
export const SETINITIALDATA = "SETINITIALDATA";
export const SHOWDETAIL = "SHOWDETAIL";
export const SLIDEPHOTO = "SLIDEPHOTO";
export const SETWEATHER = "SETWEATHER";